/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Published Courses */
        get: operations["list_published_courses_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_courses__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{slug}/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lesson Detail
         * @description Lesson detail, gated by ownership. Admins see any lesson; everyone else
         *     must own the course. Returns 404 (not 403) for a non-existent course/lesson
         *     so we don't leak which slugs exist.
         */
        get: operations["get_lesson_detail_courses__slug__lessons__lesson_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Courses
         * @description Courses the current user owns (has an entitlement for).
         */
        get: operations["my_courses_me_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/purchases/{purchase_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Purchase
         * @description One of the user's own orders, so the checkout return page can tell a
         *     confirmed payment from a pending or failed one. Someone else's order is a
         *     404, so ids can't be probed.
         */
        get: operations["my_purchase_me_purchases__purchase_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Checkout */
        post: operations["create_checkout_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/freedompay/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Freedompay Result */
        post: operations["freedompay_result_webhooks_freedompay_result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/kinescope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kinescope Status */
        post: operations["kinescope_status_webhooks_kinescope_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/video/{lesson_id}/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Video Token */
        post: operations["create_video_token_video__lesson_id__token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drm/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drm Auth */
        post: operations["drm_auth_drm_auth_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materials/{material_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Material */
        get: operations["download_material_materials__material_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/entitlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant Entitlement
         * @description Manually grant a user access to a course. Idempotent — re-granting an
         *     existing entitlement returns it rather than erroring.
         */
        post: operations["grant_entitlement_admin_entitlements_post"];
        /**
         * Revoke Entitlement
         * @description Take a course away: a manual grant, or access kept after a refund. The
         *     purchase history is left as it is.
         */
        delete: operations["revoke_entitlement_admin_entitlements_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Course */
        post: operations["add_course_admin_courses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Course
         * @description The full tree including video ids, which no public route exposes.
         */
        get: operations["read_course_admin_courses__course_id__get"];
        put?: never;
        post?: never;
        /** Remove Course */
        delete: operations["remove_course_admin_courses__course_id__delete"];
        options?: never;
        head?: never;
        /** Edit Course */
        patch: operations["edit_course_admin_courses__course_id__patch"];
        trace?: never;
    };
    "/admin/courses/{course_id}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Module */
        post: operations["add_module_admin_courses__course_id__modules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/modules/{module_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Module */
        delete: operations["remove_module_admin_modules__module_id__delete"];
        options?: never;
        head?: never;
        /** Edit Module */
        patch: operations["edit_module_admin_modules__module_id__patch"];
        trace?: never;
    };
    "/admin/modules/{module_id}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Lesson */
        post: operations["add_lesson_admin_modules__module_id__lessons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Lesson */
        delete: operations["remove_lesson_admin_lessons__lesson_id__delete"];
        options?: never;
        head?: never;
        /**
         * Edit Lesson
         * @description Setting kinescope_video_id here links a video that already exists in
         *     Kinescope. Uploading a new one goes through /admin/lessons/{id}/video.
         */
        patch: operations["edit_lesson_admin_lessons__lesson_id__patch"];
        trace?: never;
    };
    "/admin/materials/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Upload Url */
        post: operations["create_upload_url_admin_materials_upload_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Material */
        post: operations["add_material_admin_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Material */
        delete: operations["remove_material_admin_materials__material_id__delete"];
        options?: never;
        head?: never;
        /** Edit Material */
        patch: operations["edit_material_admin_materials__material_id__patch"];
        trace?: never;
    };
    "/admin/storage/sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sweep Storage
         * @description Find R2 files no material points at, and delete them only if apply=true.
         *
         *     A dry run by default, so an admin page can show what would go before
         *     anything does.
         */
        post: operations["sweep_storage_admin_storage_sweep_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Users
         * @description Accounts whose email contains `email`, ignoring case, newest first.
         */
        get: operations["find_users_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read User
         * @description An account with every course it owns and every payment it attempted.
         */
        get: operations["read_user_admin_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit User */
        patch: operations["edit_user_admin_users__user_id__patch"];
        trace?: never;
    };
    "/admin/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Purchases
         * @description Transaction history, newest first. Filter by part of the buyer's email,
         *     by course, or by status; pending rows are abandoned checkouts.
         */
        get: operations["find_purchases_admin_purchases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/purchases/{purchase_id}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refund
         * @description Record a refund made in FreedomPay's merchant cabinet. This sends no
         *     money: it marks the purchase refunded and, if asked, takes the course away.
         */
        post: operations["refund_admin_purchases__purchase_id__refund_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/lessons/{lesson_id}/video/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Video */
        post: operations["upload_video_admin_lessons__lesson_id__video_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/lessons/{lesson_id}/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lesson Video
         * @description Where the lesson's video stands. A pending upload is checked with
         *     Kinescope and swapped in if processing has finished.
         */
        get: operations["lesson_video_admin_lessons__lesson_id__video_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/lessons/{lesson_id}/video/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Discard Pending Video */
        delete: operations["discard_pending_video_admin_lessons__lesson_id__video_pending_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** CheckoutRequest */
        CheckoutRequest: {
            /** Course Id */
            course_id: number;
        };
        /**
         * CheckoutResponse
         * @description What the frontend needs to send the buyer to FreedomPay's hosted page.
         */
        CheckoutResponse: {
            /** Purchase Id */
            purchase_id: number;
            /** Payment Id */
            payment_id: string;
            /** Redirect Url */
            redirect_url: string;
            /** Amount */
            amount: string;
            currency: components["schemas"]["Currency"];
            status: components["schemas"]["PurchaseStatus"];
        };
        /** CourseAdmin */
        CourseAdmin: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** Segment */
            segment?: string | null;
            /** Price */
            price: string;
            currency: components["schemas"]["Currency"];
            status: components["schemas"]["CourseStatus"];
            /** Cover */
            cover?: string | null;
            /** Learning Outcomes */
            learning_outcomes?: string | null;
            /** Requirements */
            requirements?: string | null;
            /**
             * Modules
             * @default []
             */
            modules: components["schemas"]["ModuleAdminWithMaterials"][];
            /**
             * Materials
             * @default []
             */
            materials: components["schemas"]["MaterialAdmin"][];
        };
        /** CourseCreate */
        CourseCreate: {
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** Learning Outcomes */
            learning_outcomes?: string | null;
            /** Requirements */
            requirements?: string | null;
            /** Segment */
            segment?: string | null;
            /**
             * Price
             * @default 0
             */
            price: number | string;
            /** @default KGS */
            currency: components["schemas"]["Currency"];
            /** @default draft */
            status: components["schemas"]["CourseStatus"];
            /** Cover */
            cover?: string | null;
        };
        /** CourseDetail */
        CourseDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** Segment */
            segment?: string | null;
            /** Price */
            price: string;
            currency: components["schemas"]["Currency"];
            status: components["schemas"]["CourseStatus"];
            /** Cover */
            cover?: string | null;
            /** Learning Outcomes */
            learning_outcomes?: string | null;
            /** Requirements */
            requirements?: string | null;
            /**
             * Modules
             * @default []
             */
            modules: components["schemas"]["ModulePublic"][];
            /**
             * Materials
             * @default []
             */
            materials: components["schemas"]["MaterialPublic"][];
        };
        /** CourseListItem */
        CourseListItem: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** Segment */
            segment?: string | null;
            /** Price */
            price: string;
            currency: components["schemas"]["Currency"];
            status: components["schemas"]["CourseStatus"];
            /** Cover */
            cover?: string | null;
        };
        /**
         * CourseStatus
         * @enum {string}
         */
        CourseStatus: "draft" | "published";
        /** CourseUpdate */
        CourseUpdate: {
            /** Title */
            title?: string | null;
            /** Slug */
            slug?: string | null;
            /** Description */
            description?: string | null;
            /** Learning Outcomes */
            learning_outcomes?: string | null;
            /** Requirements */
            requirements?: string | null;
            /** Segment */
            segment?: string | null;
            /** Price */
            price?: number | string | null;
            currency?: components["schemas"]["Currency"] | null;
            status?: components["schemas"]["CourseStatus"] | null;
            /** Cover */
            cover?: string | null;
        };
        /**
         * Currency
         * @enum {string}
         */
        Currency: "KGS" | "KZT" | "UZS" | "USD";
        /**
         * DrmAuthRequest
         * @description Kinescope's playback check. Fields are optional so a malformed body
         *     answers 400 on our terms rather than FastAPI's 422.
         */
        DrmAuthRequest: {
            /** Id */
            id?: string | null;
            /** Token */
            token?: string | null;
            /** Type */
            type?: string | null;
            /** Ip */
            ip?: string | null;
            /** User Agent */
            user_agent?: string | null;
        };
        /**
         * DrmTokenResponse
         * @description Everything the player needs. The video id has been withheld from every
         *     catalog response up to this point — owning the course is what releases it.
         */
        DrmTokenResponse: {
            /** Video Id */
            video_id: string;
            /** Drm Auth Token */
            drm_auth_token: string;
            /** Expires In */
            expires_in: number;
        };
        /** EntitlementRead */
        EntitlementRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Course Id */
            course_id: number;
            /**
             * Granted At
             * Format: date-time
             */
            granted_at: string;
            /** Source Purchase Id */
            source_purchase_id?: number | null;
        };
        /**
         * Gateway
         * @enum {string}
         */
        Gateway: "freedompay" | "manual";
        /** GrantRequest */
        GrantRequest: {
            /** User Id */
            user_id: number;
            /** Course Id */
            course_id: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KinescopeWebhook
         * @description Kinescope's status notification. Only the video id is used, to pick which
         *     lesson to re-check; the status itself is read back from the API.
         */
        KinescopeWebhook: {
            /** Event */
            event?: string | null;
            data?: components["schemas"]["KinescopeWebhookData"] | null;
        };
        /** KinescopeWebhookData */
        KinescopeWebhookData: {
            /** Id */
            id?: string | null;
            /** Status */
            status?: string | null;
        };
        /**
         * LessonAdmin
         * @description Unlike LessonPublic and LessonDetail, this one does show the video id —
         *     the author is the one person who needs to see what's attached.
         */
        LessonAdmin: {
            /** Id */
            id: number;
            /** Module Id */
            module_id: number;
            /** Title */
            title: string;
            /** Order */
            order: number;
            /** Description */
            description?: string | null;
            /** Duration */
            duration?: number | null;
            /** Kinescope Video Id */
            kinescope_video_id?: string | null;
            /** Pending Video Id */
            pending_video_id?: string | null;
        };
        /** LessonAdminWithMaterials */
        LessonAdminWithMaterials: {
            /** Id */
            id: number;
            /** Module Id */
            module_id: number;
            /** Title */
            title: string;
            /** Order */
            order: number;
            /** Description */
            description?: string | null;
            /** Duration */
            duration?: number | null;
            /** Kinescope Video Id */
            kinescope_video_id?: string | null;
            /** Pending Video Id */
            pending_video_id?: string | null;
            /**
             * Materials
             * @default []
             */
            materials: components["schemas"]["MaterialAdmin"][];
        };
        /** LessonCreate */
        LessonCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Order */
            order?: number | null;
            /** Duration */
            duration?: number | null;
            /** Kinescope Video Id */
            kinescope_video_id?: string | null;
        };
        /**
         * LessonDetail
         * @description Returned only to a user who owns the course (or an admin). Still no raw
         *     kinescope id — playback goes through the DRM token endpoint (Day 8). This
         *     just confirms access and whether a video is attached.
         */
        LessonDetail: {
            /** Id */
            id: number;
            /** Module Id */
            module_id: number;
            /** Title */
            title: string;
            /** Order */
            order: number;
            /** Description */
            description?: string | null;
            /** Duration */
            duration?: number | null;
            /** Video Available */
            video_available: boolean;
            /**
             * Materials
             * @default []
             */
            materials: components["schemas"]["MaterialPublic"][];
        };
        /** LessonPublic */
        LessonPublic: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Order */
            order: number;
            /** Description */
            description?: string | null;
            /** Duration */
            duration?: number | null;
            /**
             * Materials
             * @default []
             */
            materials: components["schemas"]["MaterialPublic"][];
        };
        /** LessonUpdate */
        LessonUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Order */
            order?: number | null;
            /** Duration */
            duration?: number | null;
            /** Kinescope Video Id */
            kinescope_video_id?: string | null;
        };
        /** LessonVideo */
        LessonVideo: {
            /** Video Id */
            video_id?: string | null;
            /** Pending Video Id */
            pending_video_id?: string | null;
            /** Pending Status */
            pending_status?: string | null;
            /** State */
            state?: ("in_progress" | "complete" | "failed") | null;
            /** Duration */
            duration?: number | null;
        };
        /** MaterialAdmin */
        MaterialAdmin: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            type: components["schemas"]["MaterialType"];
            /** Storage Key */
            storage_key: string;
            /** Course Id */
            course_id?: number | null;
            /** Lesson Id */
            lesson_id?: number | null;
        };
        /** MaterialCreate */
        MaterialCreate: {
            /** Title */
            title: string;
            /** Storage Key */
            storage_key: string;
            type?: components["schemas"]["MaterialType"] | null;
            /** Course Id */
            course_id?: number | null;
            /** Lesson Id */
            lesson_id?: number | null;
        };
        /**
         * MaterialDownload
         * @description A short-lived link. Deliberately not stored anywhere — ask again when it
         *     expires rather than caching it.
         */
        MaterialDownload: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            type: components["schemas"]["MaterialType"];
            /** Filename */
            filename: string;
            /** Url */
            url: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * MaterialPublic
         * @description What a material is called, never where it's stored. The file itself comes
         *     from /materials/{id}/download, which checks ownership.
         */
        MaterialPublic: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            type: components["schemas"]["MaterialType"];
        };
        /**
         * MaterialType
         * @enum {string}
         */
        MaterialType: "pdf" | "zip" | "link" | "other";
        /**
         * MaterialUpdate
         * @description Title and type only.
         *
         *     storage_key and the parent are fixed at creation: repointing a row would
         *     strand the uploaded object, and moving a material to another course would
         *     quietly hand it to a different set of owners.
         */
        MaterialUpdate: {
            /** Title */
            title?: string | null;
            type?: components["schemas"]["MaterialType"] | null;
        };
        /**
         * MaterialUploadRequest
         * @description Only the filename — the server picks where the bytes actually land.
         */
        MaterialUploadRequest: {
            /** Filename */
            filename: string;
        };
        /** MaterialUploadTarget */
        MaterialUploadTarget: {
            /** Storage Key */
            storage_key: string;
            /** Url */
            url: string;
            /** Expires In */
            expires_in: number;
        };
        /** ModuleAdmin */
        ModuleAdmin: {
            /** Id */
            id: number;
            /** Course Id */
            course_id: number;
            /** Title */
            title: string;
            /** Order */
            order: number;
            /** Description */
            description?: string | null;
            /**
             * Lessons
             * @default []
             */
            lessons: components["schemas"]["LessonAdmin"][];
        };
        /** ModuleAdminWithMaterials */
        ModuleAdminWithMaterials: {
            /** Id */
            id: number;
            /** Course Id */
            course_id: number;
            /** Title */
            title: string;
            /** Order */
            order: number;
            /** Description */
            description?: string | null;
            /**
             * Lessons
             * @default []
             */
            lessons: components["schemas"]["LessonAdminWithMaterials"][];
        };
        /** ModuleCreate */
        ModuleCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Order */
            order?: number | null;
        };
        /** ModulePublic */
        ModulePublic: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Order */
            order: number;
            /** Description */
            description?: string | null;
            /**
             * Lessons
             * @default []
             */
            lessons: components["schemas"]["LessonPublic"][];
        };
        /** ModuleUpdate */
        ModuleUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Order */
            order?: number | null;
        };
        /**
         * MyPurchase
         * @description A buyer's own order, for the page FreedomPay sends them back to. The
         *     redirect proves nothing; this is what the payment callback recorded.
         */
        MyPurchase: {
            /** Id */
            id: number;
            /** Course Id */
            course_id: number;
            /** Amount */
            amount: string;
            currency: components["schemas"]["Currency"];
            status: components["schemas"]["PurchaseStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OwnedCourseAdmin */
        OwnedCourseAdmin: {
            /** Course Id */
            course_id: number;
            /** Course Title */
            course_title: string;
            /**
             * Granted At
             * Format: date-time
             */
            granted_at: string;
            /** Source Purchase Id */
            source_purchase_id?: number | null;
        };
        /** Page[PurchaseAdmin] */
        Page_PurchaseAdmin_: {
            /** Items */
            items: components["schemas"]["PurchaseAdmin"][];
            /** Total */
            total: number;
        };
        /** Page[UserAdmin] */
        Page_UserAdmin_: {
            /** Items */
            items: components["schemas"]["UserAdmin"][];
            /** Total */
            total: number;
        };
        /** PurchaseAdmin */
        PurchaseAdmin: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** User Email */
            user_email: string;
            /** Course Id */
            course_id: number;
            /** Course Title */
            course_title: string;
            gateway: components["schemas"]["Gateway"];
            /** Gateway Txn Id */
            gateway_txn_id?: string | null;
            /** Amount */
            amount: string;
            currency: components["schemas"]["Currency"];
            status: components["schemas"]["PurchaseStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Refunded At */
            refunded_at?: string | null;
            /** Refunded By */
            refunded_by?: number | null;
            /** Refund Note */
            refund_note?: string | null;
        };
        /**
         * PurchaseStatus
         * @enum {string}
         */
        PurchaseStatus: "pending" | "paid" | "failed" | "refunded";
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RefundRequest
         * @description A refund already made in FreedomPay's merchant cabinet.
         */
        RefundRequest: {
            /** Revoke Access */
            revoke_access: boolean;
            /** Note */
            note?: string | null;
        };
        /** SweepReport */
        SweepReport: {
            /** Scanned */
            scanned: number;
            /** Orphan Count */
            orphan_count: number;
            /** Orphans */
            orphans: string[];
            /** Deleted */
            deleted: number;
            /** Applied */
            applied: boolean;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserAdmin */
        UserAdmin: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserAdminDetail */
        UserAdminDetail: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Owned Courses
             * @default []
             */
            owned_courses: components["schemas"]["OwnedCourseAdmin"][];
            /**
             * Purchases
             * @default []
             */
            purchases: components["schemas"]["PurchaseAdmin"][];
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["UserRole"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "student" | "admin";
        /**
         * UserUpdate
         * @description What an admin can change on an account. The email stays its owner's, and
         *     any other field sent is a 422 rather than silently ignored.
         */
        UserUpdate: {
            role?: components["schemas"]["UserRole"] | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VideoUploadRequest */
        VideoUploadRequest: {
            /** Filename */
            filename: string;
            /** Filesize */
            filesize: number;
        };
        /**
         * VideoUploadTarget
         * @description Give `endpoint` to tus-js-client. It takes no token.
         */
        VideoUploadTarget: {
            /** Video Id */
            video_id: string;
            /** Endpoint */
            endpoint: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_published_courses_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseListItem"][];
                };
            };
        };
    };
    get_course_courses__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_detail_courses__slug__lessons__lesson_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_courses_me_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseListItem"][];
                };
            };
        };
    };
    my_purchase_me_purchases__purchase_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyPurchase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_checkout_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    freedompay_result_webhooks_freedompay_result_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    kinescope_status_webhooks_kinescope_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KinescopeWebhook"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_video_token_video__lesson_id__token_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrmTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drm_auth_drm_auth_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DrmAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_material_materials__material_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialDownload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_entitlement_admin_entitlements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitlementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_entitlement_admin_entitlements_delete: {
        parameters: {
            query: {
                user_id: number;
                course_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_course_admin_courses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_course_admin_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_course_admin_courses__course_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_course_admin_courses__course_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_module_admin_courses__course_id__modules_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_module_admin_modules__module_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_module_admin_modules__module_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_lesson_admin_modules__module_id__lessons_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_lesson_admin_lessons__lesson_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_lesson_admin_lessons__lesson_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_url_admin_materials_upload_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialUploadTarget"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_material_admin_materials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_material_admin_materials__material_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_material_admin_materials__material_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sweep_storage_admin_storage_sweep_post: {
        parameters: {
            query?: {
                apply?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SweepReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_users_admin_users_get: {
        parameters: {
            query?: {
                email?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserAdmin_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_user_admin_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAdminDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_user_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_purchases_admin_purchases_get: {
        parameters: {
            query?: {
                email?: string | null;
                course_id?: number | null;
                status?: components["schemas"]["PurchaseStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PurchaseAdmin_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refund_admin_purchases__purchase_id__refund_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchase_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseAdmin"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_video_admin_lessons__lesson_id__video_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoUploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoUploadTarget"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lesson_video_admin_lessons__lesson_id__video_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonVideo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_pending_video_admin_lessons__lesson_id__video_pending_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
